#!/bin/zsh


ZSH_SPACESHIP_CLOUD_CACHE_TIMEOUT="${ZSH_SPACESHIP_CLOUD_CACHE_TIMEOUT=3600}"

ZSH_SPACESHIP_AWS_USE_CLI="${ZSH_SPACESHIP_AWS_USE_CLI=false}"
ZSH_SPACESHIP_GCLOUD_USE_CLI="${ZSH_SPACESHIP_GCLOUD_USE_CLI=false}"

ZSH_SPACESHIP_DIR_SHOW="${ZSH_SPACESHIP_DIR_SHOW=true}"

ZSH_SPACESHIP_NODE_SHOW="${ZSH_SPACESHIP_NODE_SHOW=true}"
ZSH_SPACESHIP_JAVA_SHOW="${ZSH_SPACESHIP_JAVA_SHOW=true}"
ZSH_SPACESHIP_GOLANG_SHOW="${ZSH_SPACESHIP_GOLANG_SHOW=true}"
ZSH_SPACESHIP_DOTNET_SHOW="${ZSH_SPACESHIP_DOTNET_SHOW=true}"
ZSH_SPACESHIP_PYTHON_SHOW="${ZSH_SPACESHIP_PYTHON_SHOW=true}"
ZSH_SPACESHIP_VENV_SHOW="${ZSH_SPACESHIP_VENV_SHOW=true}"
ZSH_SPACESHIP_PACKAGE_SHOW="${ZSH_SPACESHIP_PACKAGE_SHOW=true}"

ZSH_SPACESHIP_EXEC_TIME_SHOW="${ZSH_SPACESHIP_EXEC_TIME_SHOW=true}"
ZSH_SPACESHIP_TIME_SHOW="${ZSH_SPACESHIP_TIME_SHOW=true}"
ZSH_SPACESHIP_DOCKER_SHOW="${ZSH_SPACESHIP_DOCKER_SHOW=true}"

ZSH_SPACESHIP_NODE_SYMBOL="${ZSH_SPACESHIP_NODE_SYMBOL=\ued0d }"
ZSH_SPACESHIP_JAVA_SYMBOL="${ZSH_SPACESHIP_JAVA_SYMBOL=\uedaf }"
ZSH_SPACESHIP_GOLANG_SYMBOL="${ZSH_SPACESHIP_GOLANG_SYMBOL=\ue626 }"
ZSH_SPACESHIP_DOTNET_SYMBOL="${ZSH_SPACESHIP_DOTNET_SYMBOL=\ue648 }"
ZSH_SPACESHIP_PYTHON_SYMBOL="${ZSH_SPACESHIP_PYTHON_SYMBOL=\ue606 }"
ZSH_SPACESHIP_VENV_SYMBOL="${ZSH_SPACESHIP_VENV_SYMBOL=}"
ZSH_SPACESHIP_PACKAGE_SYMBOL="${ZSH_SPACESHIP_PACKAGE_SYMBOL=\ueb29 }"

ZSH_SPACESHIP_DOCKER_SYMBOL="${ZSH_SPACESHIP_DOCKER_SYMBOL=\uf21f }"
ZSH_SPACESHIP_AWS_SYMBOL="${ZSH_SPACESHIP_AWS_SYMBOL=\uf0ef }"
ZSH_SPACESHIP_GCLOUD_SYMBOL="${ZSH_SPACESHIP_GCLOUD_SYMBOL=\uf1a0 }"

ZSH_SPACESHIP_LOCATION_COLOR="${ZSH_SPACESHIP_LOCATION_COLOR=39}"

ZSH_SPACESHIP_LANGUAGE_COLOR="${ZSH_SPACESHIP_LANGUAGE_COLOR=208}"
ZSH_SPACESHIP_CLOUD_COLOR="${ZSH_SPACESHIP_CLOUD_COLOR=blue}"
ZSH_SPACESHIP_CONTAINER_COLOR="${ZSH_SPACESHIP_CONTAINER_COLOR=cyan}"
ZSH_SPACESHIP_TIME_COLOR="${ZSH_SPACESHIP_TIME_COLOR=yellow}"