#!/bin/zsh

local promptDir="${0:A:h}"
source "$promptDir/config.zsh" || return

function spaceship_aws_color() {
  if [[ "$ZSH_SPACESHIP_AWS_USE_CLI" == false ]]; then
    echo $ZSH_SPACESHIP_CLOUD_CONNECTED_COLOR
    return
  fi

  local tmp_dir="${promptDir}/tmp"
  mkdir -p "$tmp_dir"
  
  local cache_file="${tmp_dir}/spaceship_aws_status"

  if [[ "$ZSH_SPACESHIP_CLOUD_CACHE" == true ]]; then
    if [[ -f "$cache_file" && $(($(date +%s) - $(stat -f %m "$cache_file"))) -lt $ZSH_SPACESHIP_CLOUD_CACHE_TIMEOUT ]]; then
      cat "$cache_file"
      return
    fi
  fi

  {
    local active_account=$(aws sts get-caller-identity 2>/dev/null)
    if [[ -n "$active_account" ]]; then
      echo $ZSH_SPACESHIP_CLOUD_CONNECTED_COLOR | tee "$cache_file" 2>/dev/null
    else
      echo $ZSH_SPACESHIP_CLOUD_DISCONNECTED_COLOR | tee "$cache_file" 2>/dev/null
    fi
  } &
}

function spaceship_gcloud_color() {
  if [[ "$ZSH_SPACESHIP_GCLOUD_USE_CLI" == false ]]; then
    echo $ZSH_SPACESHIP_CLOUD_CONNECTED_COLOR
    return
  fi
  
  local tmp_dir="${promptDir}/tmp"
  mkdir -p "$tmp_dir"

  local cache_file="${tmp_dir}/spaceship_gcloud_status"

  if [[ "$ZSH_SPACESHIP_CLOUD_CACHE" == true ]]; then
    if [[ -f "$cache_file" && $(($(date +%s) - $(stat -f %m "$cache_file"))) -lt $ZSH_SPACESHIP_CLOUD_CACHE_TIMEOUT ]]; then
      cat "$cache_file"
      return
    fi
  fi

  {
    local active_account=$(gcloud auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null)
    if [[ -n "$active_account" ]]; then
      echo $ZSH_SPACESHIP_CLOUD_CONNECTED_COLOR | tee "$cache_file" 2>/dev/null
    else
      echo $ZSH_SPACESHIP_CLOUD_DISCONNECTED_COLOR | tee "$cache_file" 2>/dev/null
    fi
  } &
}

ZSH_SPACESHIP_OS_ICON_COLOR=$ZSH_SPACESHIP_LOCATION_COLOR

SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_LOCK_SYMBOL=$ZSH_SPACESHIP_DIR_LOCK_SYMBOL
SPACESHIP_DIR_SHOW=$ZSH_SPACESHIP_DIR_SHOW
SPACESHIP_DIR_COLOR=$ZSH_SPACESHIP_LOCATION_COLOR
 
SPACESHIP_NODE_PREFIX=""
SPACESHIP_NODE_SYMBOL=$ZSH_SPACESHIP_NODE_SYMBOL
SPACESHIP_NODE_SHOW=$ZSH_SPACESHIP_NODE_SHOW
SPACESHIP_NODE_COLOR=$ZSH_SPACESHIP_LANGUAGE_COLOR

SPACESHIP_JAVA_PREFIX=""
SPACESHIP_JAVA_SYMBOL=$ZSH_SPACESHIP_JAVA_SYMBOL
SPACESHIP_JAVA_SHOW=$ZSH_SPACESHIP_JAVA_SHOW
SPACESHIP_JAVA_COLOR=$ZSH_SPACESHIP_LANGUAGE_COLOR
 
SPACESHIP_GOLANG_PREFIX=""
SPACESHIP_GOLANG_SYMBOL=$ZSH_SPACESHIP_GOLANG_SYMBOL
SPACESHIP_GOLANG_SHOW=$ZSH_SPACESHIP_GOLANG_SHOW
SPACESHIP_GOLANG_COLOR=$ZSH_SPACESHIP_LANGUAGE_COLOR
 
SPACESHIP_DOTNET_PREFIX=""
SPACESHIP_DOTNET_SYMBOL=$ZSH_SPACESHIP_DOTNET_SYMBOL
SPACESHIP_DOTNET_SHOW=$ZSH_SPACESHIP_DOTNET_SHOW
SPACESHIP_DOTNET_COLOR=$ZSH_SPACESHIP_LANGUAGE_COLOR
 
SPACESHIP_PYTHON_PREFIX=""
SPACESHIP_PYTHON_SYMBOL=$ZSH_SPACESHIP_PYTHON_SYMBOL
SPACESHIP_PYTHON_SHOW=$ZSH_SPACESHIP_PYTHON_SHOW
SPACESHIP_PYTHON_COLOR=$ZSH_SPACESHIP_LANGUAGE_COLOR
 
SPACESHIP_VENV_GENERIC_NAMES="none"
SPACESHIP_VENV_PREFIX=""
SPACESHIP_VENV_SYMBOL=$ZSH_SPACESHIP_VENV_SYMBOL
SPACESHIP_VENV_SHOW=$ZSH_SPACESHIP_VENV_SHOW
SPACESHIP_VENV_COLOR=$ZSH_SPACESHIP_LANGUAGE_COLOR

SPACESHIP_PACKAGE_PREFIX=""
SPACESHIP_PACKAGE_SYMBOL=$ZSH_SPACESHIP_PACKAGE_SYMBOL
SPACESHIP_PACKAGE_SHOW=$ZSH_SPACESHIP_PACKAGE_SHOW

SPACESHIP_EXEC_TIME_ELAPSED=5
SPACESHIP_EXEC_TIME_PREFIX=""
SPACESHIP_EXEC_TIME_SHOW=$ZSH_SPACESHIP_EXEC_TIME_SHOW
SPACESHIP_EXEC_COLOR=$ZSH_SPACESHIP_TIME_COLOR

SPACESHIP_TIME_PREFIX=""
SPACESHIP_TIME_SHOW=$SPACESHIP_TIME_SHOW
SPACESHIP_TIME_COLOR=$ZSH_SPACESHIP_TIME_COLOR

SPACESHIP_DOCKER_ASYNC=true
SPACESHIP_DOCKER_PREFIX=""
SPACESHIP_DOCKER_SYMBOL=$ZSH_SPACESHIP_DOCKER_SYMBOL
SPACESHIP_DOCKER_SHOW=$ZSH_SPACESHIP_DOCKER_SHOW
SPACESHIP_DOCKER_COLOR=$ZSH_SPACESHIP_CONTAINER_COLOR

SPACESHIP_AWS_ASYNC=true
SPACESHIP_AWS_PREFIX=""
SPACESHIP_AWS_SYMBOL=$ZSH_SPACESHIP_AWS_SYMBOL
SPACESHIP_AWS_SHOW=$ZSH_SPACESHIP_AWS_SHOW
SPACESHIP_AWS_COLOR=$(spaceship_gcloud_color)

SPACESHIP_GCLOUD_ASYNC=true
SPACESHIP_GCLOUD_PREFIX=""
SPACESHIP_GCLOUD_SYMBOL=$ZSH_SPACESHIP_GCLOUD_SYMBOL
SPACESHIP_GCLOUD_SHOW=$ZSH_SPACESHIP_GCLOUD_SHOW
SPACESHIP_GCLOUD_COLOR=$(spaceship_gcloud_color)

if [[ $TERM_PROGRAM == "WarpTerminal" ]]; then
    SPACESHIP_PROMPT_ASYNC=false
fi

ZSH_SPACESHIP_FOLDER="${ZSH_SPACESHIP_FOLDER=$(brew --prefix)/opt/spaceship}"
source "$ZSH_SPACESHIP_FOLDER/spaceship.zsh-theme"|| return

source "$promptDir/git/git-p10k.zsh" || return
source "$promptDir/os-icon/os-icon.zsh" || return

SPACESHIP_PROMPT_ORDER=(
  os_icon
  user
  host
  dir
  node
  java
  golang
  dotnet
  python
  venv
  package
  #ansible
  #terraform
  git_p10k
  async
  line_sep
  battery
  jobs
  exit_code
  sudo
  char
)
 
SPACESHIP_RPROMPT_ORDER=(
  exec_time
  docker
  #docker_compose
  #kubectl
  aws
  gcloud
  #azure
  #ibmcloud
  time
)