name: CI/CD
on:
  push:
    branches: [main]
jobs:
  ci-cd:
    permissions:
      security-events: write
      contents: write
      id-token: write
    uses: tarsilla-app/workflows/.github/workflows/static.yml@main
    with:
      publish: |
        {
          "brew": true
        }